export const LSC_LIST = [
  { id: 1, name: 'Adirondack Swimming' },
  { id: 3, name: 'Allegheny Mountain' },
  { id: 4, name: 'Arizona Swimming' },
  { id: 5, name: 'Arkansas Swimming' },
  { id: 6, name: 'Border Swimming' },
  { id: 8, name: 'Central California' },
  { id: 9, name: 'Colorado Swimming' },
  { id: 10, name: 'Connecticut Swimming' },
  { id: 12, name: 'Florida Gold Coast' },
  { id: 13, name: 'Florida Swimming' },
  { id: 14, name: 'Georgia Swimming' },
  { id: 15, name: 'Gulf Swimming' },
  { id: 16, name: 'Hawaiian Swimming' },
  { id: 17, name: 'Illinois Swimming' },
  { id: 18, name: 'Indiana Swimming' },
  { id: 19, name: 'Inland Empire Swimming' },
  { id: 20, name: 'Iowa Swimming' },
  { id: 21, name: 'Kentucky Swimming' },
  { id: 22, name: 'Lake Erie Swimming' },
  { id: 23, name: 'Louisiana Swimming' },
  { id: 24, name: 'Maine Swimming' },
  { id: 25, name: 'Maryland Swimming' },
  { id: 26, name: 'Metropolitan Swimming' },
  { id: 27, name: 'Michigan Swimming' },
  { id: 28, name: 'Middle Atlantic Swimming' },
  { id: 29, name: 'Midwestern Swimming' },
  { id: 30, name: 'Minnesota Swimming' },
  { id: 31, name: 'Mississippi Swimming' },
  { id: 32, name: 'Missouri Valley Swimming' },
  { id: 33, name: 'Montana Swimming' },
  { id: 34, name: 'New England Swimming' },
  { id: 35, name: 'New Jersey Swimming' },
  { id: 36, name: 'New Mexico Swimming' },
  { id: 37, name: 'Niagara Swimming' },
  { id: 38, name: 'North Carolina Swimming' },
  { id: 39, name: 'North Dakota Swimming' },
  { id: 40, name: 'North Texas Swimming' },
  { id: 41, name: 'Ohio Swimming' },
  { id: 43, name: 'Oklahoma Swimming' },
  { id: 44, name: 'Oregon Swimming' },
  { id: 45, name: 'Ozark Swimming' },
  { id: 46, name: 'Pacific Northwest' },
  { id: 47, name: 'Pacific Swimming' },
  { id: 48, name: 'Potomac Valley Swimming' },
  { id: 49, name: 'San Diego-Imperial' },
  { id: 50, name: 'Sierra Nevada Swimming' },
  { id: 51, name: 'Snake River Swimming' },
  { id: 52, name: 'South Carolina Swimming' },
  { id: 53, name: 'South Dakota Swimming' },
  { id: 54, name: 'South Texas Swimming' },
  { id: 55, name: 'Southeastern Swimming' },
  { id: 57, name: 'Southern California' },
  { id: 58, name: 'USA Swimming' },
  { id: 60, name: 'Utah Swimming' },
  { id: 61, name: 'Virginia Swimming' },
  { id: 62, name: 'West Texas Swimming' },
  { id: 63, name: 'West Virginia Swimming' },
  { id: 65, name: 'Wisconsin Swimming' },
  { id: 66, name: 'Wyoming Swimming' },
];

export function getLSCName(id) {
  const lsc = LSC_LIST.find(l => l.id === id);
  return lsc?.name || null;
}
